[package]
name = "parihsz/chrono"
description = "Custom Character Replication"
version = "1.0.13"
registry = "https://github.com/UpliftGames/wally-index"
exclude = [
     ".vscode",
     "rokit.toml",
     ".luaurc",
     "sourcemap.json",
     "selene.toml",
     "README.md",
     "docs",
     ".gitignore",
     "node_modules",
]
realm = "shared"

[dev-dependencies]
iris = "sirmallard/iris@2.5.0"
